language: python
python: 3.6
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py36-django18

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
    
# Cache environment between test runs
cache:
  directories:
    - $HOME/build/UCL-RITS/indigo_django/.tox
