language: python
python: 3.5
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
    
cache:
  directories:
    - $HOME/build/UCL-RITS/indigo_django/.tox
